
# In line with the Building model default fields
DATASET_BASE_SCHEMA = [
        {
            "id": "ext_id",
            "field": "ext_id",
            "label": {"en": "External ID"},
            "type": "string",
            "input": "text",
            "optgroup": "core",
        },
        {
            "id": "address",
            "field": "address",
            "label": {"en": "Address"},
            "type": "string",
            "input": "text",
            "optgroup": "core",
        },
        {
            "id": "geocoding_error",
            "field": "geocoding_error",
            "label": {"en": "Geocoding Error"},
            "type": "string",
            "input": "text",
            "optgroup": "metadata",
        },
        {
            "id": "street_name",
            "field": "street_name",
            "label": {"en": "Street Name"},
            "type": "string",
            "input": "text",
            "optgroup": "core",
        },
        {
            "id": "street_num",
            "field": "street_num",
            "label": {"en": "Street Number"},
            "type": "string",
            "input": "text",
            "optgroup": "core",
        },
        {
            "id": "muni",
            "field": "muni",
            "label": {"en": "Municipality"},
            "type": "string",
            "input": "text",
            "optgroup": "core",
        },
        {
            "id": "submuni",
            "field": "submuni",
            "label": {"en": "Submunicipality"},
            "type": "string",
            "input": "text",
            "optgroup": "core",
        },
        {
            "id": "admin_area_level_1",
            "field": "admin_area_level_1",
            "label": {"en": "Province"},
            "type": "string",
            "input": "text",
            "optgroup": "core",
        },
        {
            "id": "postal_code",
            "field": "postal_code",
            "label": {"en": "Postal Code"},
            "type": "string",
            "input": "text",
            "optgroup": "core",
        },
        {
            "id": "const_year",
            "field": "const_year",
            "label": {"en": "Construction Year"},
            "type": "integer",
            "input": "number",
            "optgroup": "core",
        },
        {
            "id": "num_floors",
            "field": "num_floors",
            "label": {"en": "Num. Floors"},
            "type": "integer",
            "input": "number",
            "optgroup": "core",
        },
        {
            "id": "floor_area",
            "field": "floor_area",
            "label": {"en": "Floor area"},
            "optgroup": "core",
            "type": "double",
            "input": "number",
            "validation": {"min": 0, "step": 0.01},
        },
    ]