# Generated by Django 4.1.7 on 2023-12-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="knowledge_level",
            field=models.TextField(blank=True, null=True),
        ),
    ]
