# Generated by Django 4.1.7 on 2023-12-21 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0002_user_knowledge_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="PotentialMetalBuilding",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="buildings.evalunit",
                    ),
                ),
                ("p_bldg", models.FloatField()),
                ("p_metal", models.FloatField()),
            ],
            options={
                "db_table": "metal",
            },
        ),
    ]
