# Generated by Django 4.1.7 on 2023-03-05 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_number", models.TextField()),
                ("street_name", models.TextField()),
                ("locality", models.TextField()),
                ("region", models.TextField()),
                ("province", models.TextField()),
                ("country", models.TextField()),
                ("postal_code", models.CharField(max_length=7)),
                ("formatted_address", models.TextField()),
                ("cubf", models.IntegerField()),
                ("lon", models.FloatField()),
                ("lat", models.FloatField()),
                ("date_added", models.DateTimeField(verbose_name="date added")),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                ("votes", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buildings.building",
                    ),
                ),
            ],
        ),
    ]
