# Generated by Django 4.1.7 on 2024-07-28 16:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalUnitLot',
            fields=[
                ('gid', models.TextField(primary_key=True, serialize=False)),
                ('objectid', models.BigIntegerField(blank=True, null=True)),
                ('co_mrc', models.TextField(blank=True, null=True)),
                ('code_mun', models.TextField(blank=True, null=True)),
                ('arrond', models.TextField(blank=True, null=True)),
                ('anrole', models.TextField(blank=True, null=True)),
                ('usag_predo', models.TextField(blank=True, null=True)),
                ('no_lot', models.TextField(blank=True, null=True)),
                ('nb_poly_lo', models.FloatField(blank=True, null=True)),
                ('utilisatio', models.TextField(blank=True, null=True)),
                ('id_provinc', models.TextField()),
                ('sup_totale', models.FloatField(blank=True, null=True)),
                ('descriptio', models.TextField(blank=True, null=True)),
                ('nb_logemen', models.BigIntegerField(blank=True, null=True)),
                ('nb_locaux', models.BigIntegerField(blank=True, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('dat_acqui', models.DateField(blank=True, null=True)),
                ('dat_charg', models.DateField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'lots',
            },
        ),
        migrations.RemoveField(
            model_name='evalunit',
            name='lot_geom',
        ),
        migrations.AlterField(
            model_name='evalunit',
            name='lot_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='evalunitlot',
            index=models.Index(fields=['id_provinc'], name='idx_id_provinc'),
        ),
    ]
