# Generated by Django 4.1.7 on 2023-08-14 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evalunit",
            name="cardinal_pt",
        ),
        migrations.RemoveField(
            model_name="evalunit",
            name="way_link",
        ),
        migrations.RemoveField(
            model_name="evalunit",
            name="way_type",
        ),
    ]
