# Generated by Django 4.1.7 on 2023-03-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0002_facadematerial_vote_delete_choice"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FacadeMaterial",
            new_name="Material",
        ),
    ]
