# Generated by Django 4.1.7 on 2023-08-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0003_alter_user_managers_uploadimagejob"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="data_modified",
            new_name="date_modified",
        ),
    ]
