# Generated by Django 4.1.7 on 2023-03-11 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0003_rename_facadematerial_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="date_added",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 11, 1, 1, 58, 618548, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date added",
            ),
        ),
    ]
