# Generated by Django 4.1.7 on 2023-03-12 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0004_vote_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="note",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="vote",
            name="date_added",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 12, 3, 54, 17, 818692, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date added",
            ),
        ),
    ]
