# Generated by Django 4.1.7 on 2023-08-29 18:42
# Modified by a human being shortly thereafter

from django.db import migrations, models


def migrate_facade_condition_to_boolean(apps, _):

    SurveyV1 = apps.get_model('buildings', 'SurveyV1')

    for s in SurveyV1.objects.all():

        old_value = s.facade_condition_old

        if old_value == 'unsure':
            new_value = None
        elif old_value in ['good', 'fair']:
            new_value = False
        elif old_value == 'poor':
            new_value = True

        s.facade_condition = new_value 
        s.save()


def migrate_window_wall_ratio_to_boolean(apps, _):

    SurveyV1 = apps.get_model('buildings', 'SurveyV1')

    for s in SurveyV1.objects.all():

        old_value = s.window_wall_ratio_old

        if old_value == 'unsure':
            new_value = None
        elif old_value in ['large', 'medium']:
            new_value = True
        elif old_value == 'small':
            new_value = False

        s.window_wall_ratio = new_value
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0004_rename_data_modified_vote_date_modified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyv1",
            name="structure_type",
        ),
        migrations.AddField(
            model_name="surveyv1",
            name="self_similar_cluster",
            field=models.BooleanField(null=True),
        ),
        # Method to migrate data while changing field type
        # https://stackoverflow.com/questions/39628637/convert-data-on-alterfield-django-migration
        # Rename target field to other
        # Create a new field with same name
        # Use RunPython to migrate data from old field to new
        # Remove the old field 
        migrations.RenameField(
            model_name='surveyv1',
            old_name='facade_condition',
            new_name='facade_condition_old',
        ),
        migrations.AddField(
            model_name="surveyv1",
            name="facade_condition",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_facade_condition_to_boolean),
        migrations.RemoveField(
            model_name='surveyv1',
            name='facade_condition_old',
        ),
        # Same thing for WWR
        migrations.RenameField(
            model_name='surveyv1',
            old_name='window_wall_ratio',
            new_name='window_wall_ratio_old',
        ),
        migrations.AddField(
            model_name="surveyv1",
            name="window_wall_ratio",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_window_wall_ratio_to_boolean),
        migrations.RemoveField(
            model_name='surveyv1',
            name='window_wall_ratio_old',
        ),
    ]
