# Generated by Django 4.1.7 on 2023-03-12 03:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("buildings", "0005_vote_note_alter_vote_date_added"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Material",
            new_name="BuildingMaterial",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="note",
        ),
        migrations.AlterField(
            model_name="vote",
            name="date_added",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 12, 3, 57, 12, 173636, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date added",
            ),
        ),
        migrations.CreateModel(
            name="BuildingNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 3, 12, 3, 57, 12, 173636, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="date added",
                    ),
                ),
                ("note", models.TextField(blank=True, default=None, null=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buildings.building",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
