# Generated by Django 4.1.7 on 2023-08-29 19:58

from django.db import migrations, models

# Split the previous migration into one migration data with RunPython ops
# and this one altering the schema by adding and removing fields
class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0005_remove_surveyv1_structure_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyv1",
            name="structure_type",
        ),
        migrations.AddField(
            model_name="surveyv1",
            name="self_similar_cluster",
            field=models.BooleanField(null=True),
        ),
        migrations.RemoveField(
            model_name='surveyv1',
            name='facade_condition_old',
        ),
        migrations.RemoveField(
            model_name='surveyv1',
            name='window_wall_ratio_old',
        ),
    ]
