# Generated by Django 4.1.7 on 2023-09-18 19:13

from django.db import migrations, models



def migrate_large_irregular_windows_from_boolean_to_JSONField(apps, _):

    SurveyV1 = apps.get_model('buildings', 'SurveyV1')

    for s in SurveyV1.objects.all():

        old_value = s.large_irregular_windows_old

        if old_value in [None, False]:
            new_value = None
        elif old_value is True:
            new_value = ['very_large_windows']

        s.large_irregular_windows = new_value
        s.save()


def migrate_new_or_renovated_from_boolean_to_TextField(apps, _):
    SurveyV1 = apps.get_model('buildings', 'SurveyV1')

    for s in SurveyV1.objects.all():

        old_value = s.new_or_renovated_old

        if old_value in [None, False]:
            new_value = 'no'
        elif old_value is True:
            new_value = 'recently_renovated'

        s.large_irregular_windows = new_value
        s.save()



class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0006_auto_20230829_1558"),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyv1',
            old_name='large_irregular_windows',
            new_name='large_irregular_windows_old',
        ),
        migrations.AddField(
            model_name="surveyv1",
            name="large_irregular_windows",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_large_irregular_windows_from_boolean_to_JSONField),

        migrations.RenameField(
            model_name='surveyv1',
            old_name='new_or_renovated',
            new_name='new_or_renovated_old',
        ),
        migrations.AddField(
            model_name="surveyv1",
            name="new_or_renovated",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_new_or_renovated_from_boolean_to_TextField),
    ]
