# Generated by Django 4.1.7 on 2023-03-12 03:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "buildings",
            "0006_rename_material_buildingmaterial_remove_vote_note_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="date_added",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date added"
            ),
        ),
        migrations.AlterField(
            model_name="buildingnote",
            name="date_added",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date added"
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="date_added",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date added"
            ),
        ),
    ]
