# Generated by Django 5.0.9 on 2024-11-23 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_dataset_building'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='attributes',
            new_name='attr',
        ),
    ]
