# Generated by Django 4.1.7 on 2023-09-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0007_change_large_windows_to_json_20230918_1513"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyv1",
            name="large_irregular_windows_old",
        ),
        migrations.RemoveField(
            model_name="surveyv1",
            name="new_or_renovated_old",
        ),
        migrations.AlterField(
            model_name="surveyv1",
            name="appendages",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="surveyv1",
            name="site_obstructions",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
