# Generated by Django 4.2.17 on 2025-01-27 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_building_dataset_survey_problemflag_latestviewdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfigs',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('res_page_bldg_cols', models.JSONField(blank=True, null=True)),
                ('res_page_survey_cols', models.JSONField(blank=True, null=True)),
                ('sur_page_bldg_cols', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
