# Generated by Django 5.0.9 on 2024-11-23 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_rename_attributes_building_attr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='attr',
            new_name='attrs',
        ),
    ]
