# Generated by Django 4.2.17 on 2024-12-29 22:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_dataset_created_by_survey_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedBuildingResponses',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ext_id', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('address', models.TextField()),
                ('street_name', models.TextField(null=True)),
                ('street_num', models.TextField(null=True)),
                ('street_num_2', models.TextField(blank=True, null=True)),
                ('muni', models.TextField(blank=True, null=True)),
                ('submuni', models.TextField(blank=True, null=True)),
                ('postal_code', models.TextField(blank=True, null=True)),
                ('const_year', models.SmallIntegerField(blank=True, null=True)),
                ('num_floors', models.IntegerField(blank=True, null=True)),
                ('floor_area', models.FloatField(blank=True, null=True)),
                ('attrs', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together={('name', 'dataset', 'schema', 'dataset_filter', 'surveys_filter')},
        ),
    ]
