# Generated by Django 4.2.17 on 2024-12-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_dataset_created_by_survey_created_by_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
                CREATE or replace FUNCTION jsonb_to_int_array(jsonb) RETURNS int[] AS $f$
                SELECT coalesce(array_agg(x)::int[], 
                    CASE WHEN $1 is null THEN null ELSE ARRAY[]::int[] END)
                FROM jsonb_array_elements($1) t(x);
                $f$ LANGUAGE sql IMMUTABLE;

                CREATE or replace FUNCTION jsonb_to_text_array(jsonb) RETURNS text[] AS $f$
                SELECT coalesce(array_agg(x)::text[], 
                    CASE WHEN $1 is null THEN null ELSE ARRAY[]::text[] END)
                FROM jsonb_array_elements_text($1) t(x);
                $f$ LANGUAGE sql IMMUTABLE;
            """,
            """
            drop function jsonb_to_int_array;
            drop function jsonb_to_text_array;
            """
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together={('name', 'dataset', 'dataset_filter', 'surveys_filter')},
        ),
    ]
