# Generated by Django 4.1.7 on 2023-03-12 05:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0007_alter_building_date_added_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "date_added",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date added"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaterialScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buildings.material",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="buildingnote",
            name="building",
        ),
        migrations.RemoveField(
            model_name="buildingnote",
            name="date_added",
        ),
        migrations.RemoveField(
            model_name="buildingnote",
            name="user",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="material",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="score",
        ),
        migrations.AddField(
            model_name="buildingnote",
            name="vote",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="buildings.vote",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="BuildingMaterial",
        ),
        migrations.AddField(
            model_name="materialscore",
            name="vote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="buildings.vote"
            ),
        ),
    ]
