# Generated by Django 4.2.17 on 2025-02-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_building_dataset_userconfigs_survey_problemflag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfigs',
            name='res_page_bldg_cols',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='userconfigs',
            name='res_page_survey_cols',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='userconfigs',
            name='sur_page_bldg_cols',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
