# Generated by Django 4.2.17 on 2025-01-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_database_functions_for_survey_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='modals',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
