# Generated by Django 4.1.7 on 2023-03-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "buildings",
            "0008_material_materialscore_remove_buildingnote_building_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
