# Generated by Django 5.0.9 on 2024-11-23 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_rename_attr_building_attrs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='street_num2',
            new_name='street_num_2',
        ),
    ]
