# Generated by Django 4.2.17 on 2025-04-07 02:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_remove_uploadimagejob_eval_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.TextField()),
                ('key', models.TextField()),
                ('type', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added')),
                ('metadata', models.JSONField(default=dict)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
            ],
        ),
        migrations.RemoveField(
            model_name='evalunitstreetviewimage',
            name='eval_unit',
        ),
        migrations.RemoveField(
            model_name='evalunitstreetviewimage',
            name='user',
        ),
        migrations.DeleteModel(
            name='EvalUnitSatelliteImage',
        ),
        migrations.DeleteModel(
            name='EvalUnitStreetViewImage',
        ),
    ]
