# Generated by Django 4.2.17 on 2025-02-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_alter_userconfigs_res_page_bldg_cols_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='schema',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.TextField(choices=[('IN PROGRESS', 'In Progress'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='IN PROGRESS'),
        ),
    ]
