# Generated by Django 4.1.7 on 2023-09-19 20:20

from django.db import migrations, models



def migrate_cluster_bool_to_int(apps, _):
    SurveyV1 = apps.get_model('buildings', 'SurveyV1')

    for s in SurveyV1.objects.all():

        old_value = s.self_similar_cluster_old

        if old_value is None:
            new_value = None
        elif old_value is False:
            new_value = 0
        # We don't know how many, so we'll default at 2 and manually check 
        elif old_value is True:
            new_value = 2

        s.self_similar_cluster = new_value
        s.save()



class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0008_change_large_windows_to_json__pt2"),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyv1',
            old_name='self_similar_cluster',
            new_name='self_similar_cluster_old',
        ),
        migrations.AddField(
            model_name="surveyv1",
            name="self_similar_cluster",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_cluster_bool_to_int),
    ]
