# Generated by Django 4.2.17 on 2025-03-07 01:01

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_alter_survey_schema_alter_survey_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
