# Generated by Django 4.1.7 on 2023-09-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0009_cluster_bool_to_int_p1_20230919_1620"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyv1",
            name="self_similar_cluster_old",
        ),
    ]
