# Generated by Django 4.2.17 on 2025-06-17 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_buildingimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetOnboardingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('csv_file_location', models.TextField(blank=True, help_text='Location of the uploaded CSV file', null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dataset_onboarding_jobs',
            },
        ),
    ]
