# Generated by Django 4.2.17 on 2025-01-10 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_survey_modals'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LatestViewData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added')),
                ('sv_pano', models.TextField(blank=True, null=True)),
                ('sv_heading', models.FloatField(blank=True, null=True)),
                ('sv_pitch', models.FloatField(blank=True, null=True)),
                ('sv_zoom', models.FloatField(blank=True, null=True)),
                ('marker_lat', models.FloatField(blank=True, null=True)),
                ('marker_lng', models.FloatField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
