# Generated by Django 4.1.7 on 2023-03-12 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0010_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingnote",
            name="vote",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="buildings.vote",
            ),
        ),
    ]
