# Generated by Django 4.2.17 on 2025-11-01 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_datasetonboardingjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='geocoding_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='has_streetview',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='datasetonboardingjob',
            name='attrs_schema',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='datasetonboardingjob',
            name='column_mapping',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='datasetonboardingjob',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_job', to='buildings.dataset'),
        ),
        migrations.AddField(
            model_name='datasetonboardingjob',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified'),
        ),
        migrations.AddField(
            model_name='datasetonboardingjob',
            name='has_coordinates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasetonboardingjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
