# Generated by Django 4.1.7 on 2023-09-19 20:25

import buildings.models.surveys
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0010_cluster_bool_to_int_p2_20230919_1621"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyv1",
            name="appendages",
            field=buildings.models.surveys.JSONFieldForSpecify(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="surveyv1",
            name="exterior_cladding",
            field=buildings.models.surveys.JSONFieldForSpecify(),
        ),
        migrations.AlterField(
            model_name="surveyv1",
            name="site_obstructions",
            field=buildings.models.surveys.JSONFieldForSpecify(blank=True, null=True),
        ),
    ]
