# Generated by Django 4.2.17 on 2025-11-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_datasetonboardingjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetonboardingjob',
            name='attrs_schema',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='datasetonboardingjob',
            name='column_mapping',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
