# Generated by Django 4.2.17 on 2025-11-04 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0011_building_geocoding_error_building_has_streetview_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('ext_id', 'lat', 'lng', 'address', 'muni', 'dataset')},
        ),
    ]
