# Generated by Django 4.1.7 on 2023-09-20 20:48

from django.db import migrations, models


def migrate_new_or_renovated_to_JSON(apps, _):
    SurveyV1 = apps.get_model('buildings', 'SurveyV1')

    for s in SurveyV1.objects.all():

        old_value = s.new_or_renovated_old

        # Encapsulate the old value in an array
        if old_value in [None, 'no', 'false']:
            new_value = None
        else:
            new_value = [old_value]

        s.new_or_renovated = new_value
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0011_alter_surveyv1_appendages_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyv1',
            old_name='new_or_renovated',
            new_name='new_or_renovated_old',
        ),
        migrations.AddField(
            model_name="surveyv1",
            name="new_or_renovated",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(
            migrate_new_or_renovated_to_JSON
        ),
        migrations.RemoveField(
            model_name="surveyv1",
            name="new_or_renovated_old",
        ),
    ]
