# Generated by Django 4.1.7 on 2023-03-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0012_typology_buildingtypology"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="locality",
            field=models.TextField(blank=True, null=True),
        ),
    ]
