# Generated by Django 4.1.7 on 2023-09-21 17:17

from django.db import migrations, models


def migrate_roof_geometry_to_JSON(apps, _):
    SurveyV1 = apps.get_model('buildings', 'SurveyV1')

    for s in SurveyV1.objects.all():

        old_value = s.roof_geometry_old

        # Encapsulate the old value in an array
        if old_value is None:
            new_value = None
        else:
            new_value = [old_value]

        s.roof_geometry = new_value
        s.save()

class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0012_alter_surveyv1_new_or_renovated"),
    ]

    operations = [

        migrations.RenameField(
            model_name='surveyv1',
            old_name='roof_geometry',
            new_name='roof_geometry_old',
        ),
        migrations.AddField(
            model_name="surveyv1",
            name="roof_geometry",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(
            migrate_roof_geometry_to_JSON
        ),
        migrations.RemoveField(
            model_name="surveyv1",
            name="roof_geometry_old",
        ),
    ]
