# Generated by Django 4.1.7 on 2023-10-03 18:50

from django.db import migrations
from django.contrib.gis.db import models
import django.contrib.gis.db.models.fields

from django.contrib.gis.geos import Point


def create_geo_points(apps, _):
    EvalUnit = apps.get_model('buildings', 'EvalUnit')

    for eu in EvalUnit.objects.all():
        eu.point = Point(eu.lng, eu.lat)
        eu.save()


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0013_alter_roof_geometry"),
    ]

    operations = [
        migrations.AddField(
            model_name="evalunit",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.RunPython(
            create_geo_points
        ),
        migrations.AddIndex(
            model_name="evalunit",
            index=models.Index(fields=["point"], name="point_geo_idx"),
        ),
    ]
