# Generated by Django 4.1.7 on 2023-03-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0013_alter_building_locality"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingtypology",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
