# Generated by Django 4.1.7 on 2023-11-13 16:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0014_evalunit_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="evalunit",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="hlmbuilding",
            name="address",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="hlmbuilding",
            name="lat",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="hlmbuilding",
            name="lng",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="hlmbuilding",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterModelTable(
            name="evalunit",
            table="evalunits",
        ),
        migrations.AlterModelTable(
            name="hlmbuilding",
            table="hlms",
        ),
    ]
