# Generated by Django 4.1.7 on 2023-03-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0014_buildingtypology_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="construction_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="floor_area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="max_num_floor",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="num_non_res",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="serial_number",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="type_const",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="value_prop",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="year_real_esti",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
