# Generated by Django 4.1.7 on 2023-03-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0015_building_construction_year_building_floor_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="csv_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
