# Generated by Django 4.1.7 on 2023-03-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0016_building_csv_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="serial_number",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
