# Generated by Django 4.1.7 on 2023-03-25 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0017_alter_building_serial_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingtypology",
            name="vote",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="buildings.vote"
            ),
        ),
    ]
