# Generated by Django 4.1.7 on 2023-03-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0019_building_place_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="num_dwell",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="num_rental",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
