# Generated by Django 4.1.7 on 2023-03-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0020_building_num_dwell_building_num_rental"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="lin_dim",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
