# Generated by Django 4.1.7 on 2023-03-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0021_building_area_building_lin_dim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="serial_number",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
