# Generated by Django 4.1.7 on 2023-04-16 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("buildings", "0022_alter_building_serial_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingLatestViewData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date added"
                    ),
                ),
                ("sv_pano", models.TextField(blank=True, null=True)),
                ("sv_heading", models.FloatField(blank=True, null=True)),
                ("sv_pitch", models.FloatField(blank=True, null=True)),
                ("sv_zoom", models.FloatField(blank=True, null=True)),
                ("marker_lat", models.FloatField(blank=True, null=True)),
                ("marker_lng", models.FloatField(blank=True, null=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buildings.building",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
