# Generated by Django 4.1.7 on 2023-04-17 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0023_buildinglatestviewdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoBuildingFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="buildings.vote"
                    ),
                ),
            ],
        ),
    ]
