# Generated by Django 4.1.7 on 2023-04-17 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0024_nobuildingflag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nobuildingflag",
            name="vote",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="buildings.vote"
            ),
        ),
    ]
