# Generated by Django 4.1.7 on 2023-08-02 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("buildings", "0028_rename_buildingimage_buildingsatelliteimage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date created"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="last modified"
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buildings.building",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "building")},
            },
        ),
        migrations.CreateModel(
            name="SurveyV1",
            fields=[
                (
                    "basesurvey_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="buildings.basesurvey",
                    ),
                ),
                ("has_simple_footprint", models.BooleanField()),
                ("has_simple_volume", models.BooleanField()),
                ("num_storeys", models.IntegerField(blank=True, null=True)),
                ("has_basement", models.BooleanField(blank=True, null=True)),
                ("site_obstructions", models.JSONField()),
                ("appendages", models.JSONField()),
                ("exterior_cladding", models.JSONField()),
                ("facade_condition", models.TextField(blank=True, null=True)),
                ("window_wall_ratio", models.TextField(blank=True, null=True)),
                ("large_irregular_windows", models.BooleanField(blank=True, null=True)),
                ("roof_geometry", models.TextField()),
                ("structure_type", models.TextField()),
                ("new_or_renovated", models.BooleanField(blank=True, null=True)),
            ],
            bases=("buildings.basesurvey",),
        ),
    ]
