# Generated by Django 4.1.7 on 2023-07-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0028_rename_buildingimage_buildingsatelliteimage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyV1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "q1",
                    models.CharField(
                        choices=[("Yes", "yes"), ("No", "no")], max_length=3
                    ),
                ),
                (
                    "q2",
                    models.CharField(
                        choices=[("Yes", "yes"), ("No", "no")], max_length=3
                    ),
                ),
                (
                    "q3",
                    models.CharField(
                        choices=[("Yes", "yes"), ("No", "no")], max_length=3
                    ),
                ),
                (
                    "q4",
                    models.CharField(
                        choices=[("Yes", "yes"), ("No", "no"), ("Unsure", "unsure")],
                        max_length=6,
                    ),
                ),
            ],
        ),
    ]
