# Generated by Django 4.1.7 on 2023-08-04 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0028_rename_buildingimage_buildingsatelliteimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="data_modified",
            field=models.DateTimeField(auto_now=True, verbose_name="date modified"),
        ),
        migrations.AlterField(
            model_name="vote",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date added"),
        ),
        migrations.CreateModel(
            name="SurveyV1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_simple_footprint", models.BooleanField()),
                ("has_simple_volume", models.BooleanField()),
                ("num_storeys", models.IntegerField(blank=True, null=True)),
                ("has_basement", models.BooleanField(blank=True, null=True)),
                ("site_obstructions", models.JSONField()),
                ("appendages", models.JSONField()),
                ("exterior_cladding", models.JSONField()),
                ("facade_condition", models.TextField(blank=True, null=True)),
                ("window_wall_ratio", models.TextField(blank=True, null=True)),
                ("large_irregular_windows", models.BooleanField(blank=True, null=True)),
                ("roof_geometry", models.TextField()),
                ("structure_type", models.TextField()),
                ("new_or_renovated", models.BooleanField(blank=True, null=True)),
                (
                    "vote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="buildings.vote"
                    ),
                ),
            ],
        ),
    ]
