dataset_query_1 = {
    "query": {
        "condition": "AND",
        "rules": [
            {
                "id": "const_year",
                "field": "const_year",
                "type": "date",
                "input": "text",
                "operator": "between",
                "value": [1950, 2000],
            },
            {
                "condition": "OR",
                "rules": [
                    {
                        "id": "num_floors",
                        "field": "num_floors",
                        "type": "integer",
                        "input": "number",
                        "operator": "greater",
                        "value": 1,
                    },
                    {
                        "id": "attrs__phys_link",
                        "field": "attrs__phys_link",
                        "type": "string",
                        "input": "checkbox",
                        "operator": "in",
                        "value": ["semi-detached", "row house"],
                    },
                ],
            },
        ],
        "valid": True,
    }
}


dataset_schema = [
    {
        "id": "ext_id",
        "type": "string",
        "field": "ext_id",
        "input": "text",
        "label": {"en": "External ID"},
        "optgroup": "core",
    },
    {
        "id": "address",
        "type": "string",
        "field": "address",
        "input": "text",
        "label": {"en": "Address"},
        "optgroup": "core",
    },
    {
        "id": "street_name",
        "type": "string",
        "field": "street_name",
        "input": "text",
        "label": {"en": "Street Name"},
        "optgroup": "core",
    },
    {
        "id": "street_num",
        "type": "string",
        "field": "street_num",
        "input": "text",
        "label": {"en": "Street Number"},
        "optgroup": "core",
    },
    {
        "id": "muni",
        "type": "string",
        "field": "muni",
        "input": "text",
        "label": {"en": "Municipality"},
        "optgroup": "core",
    },
    {
        "id": "submuni",
        "type": "string",
        "field": "submuni",
        "input": "text",
        "label": {"en": "Submunicipality"},
        "optgroup": "core",
    },
    {
        "id": "postal_code",
        "type": "string",
        "field": "postal_code",
        "input": "text",
        "label": {"en": "Postal Code"},
        "optgroup": "core",
    },
    {
        "id": "const_year",
        "type": "date",
        "field": "const_year",
        "label": {"en": "Construction Year"},
        "plugin": "datepicker",
        "optgroup": "core",
        "plugin_config": {
            "format": "yyyy",
            "todayBtn": "linked",
            "autoclose": True,
            "minViewMode": "years",
            "todayHighlight": True,
        },
    },
    {
        "id": "num_floors",
        "type": "integer",
        "field": "num_floors",
        "input": "number",
        "label": {"en": "Num. Floors"},
        "optgroup": "core",
    },
    {
        "id": "floor_area",
        "type": "double",
        "field": "floor_area",
        "input": "number",
        "label": {"en": "Floor area"},
        "optgroup": "core",
        "validation": {"min": 0, "step": 0.01},
    },
    {
        "id": "attrs__organism",
        "type": "string",
        "field": "attrs__organism",
        "input": "text",
        "label": {"en": "Organism"},
        "optgroup": "attributes",
    },
    {
        "id": "attrs__service_center",
        "type": "string",
        "field": "attrs__service_center",
        "input": "text",
        "label": {"en": "Service Center"},
        "optgroup": "attributes",
    },
    {
        "id": "attrs__area_footprint",
        "type": "double",
        "field": "attrs__area_footprint",
        "input": "number",
        "label": {"en": "Footprint Area"},
        "optgroup": "attributes",
        "validation": {"min": 0, "step": 0.01},
    },
    {
        "id": "attrs__area_total",
        "type": "double",
        "field": "attrs__area_total",
        "input": "number",
        "label": {"en": "Total Area"},
        "optgroup": "attributes",
        "validation": {"min": 0, "step": 0.01},
    },
    {
        "id": "attrs__ivp",
        "type": "double",
        "field": "attrs__ivp",
        "input": "number",
        "label": {"en": "IVP"},
        "optgroup": "attributes",
        "validation": {"min": 0, "step": 0.01},
    },
    {
        "id": "attrs__disrepair_state",
        "type": "string",
        "field": "attrs__disrepair_state",
        "input": "checkbox",
        "label": {"en": "Disrepair State"},
        "values": ["A", "B", "C", "D", "E"],
        "optgroup": "attributes",
    },
    {
        "id": "attrs__interest_adjust_date",
        "type": "date",
        "field": "attrs__interest_adjust_date",
        "label": {"en": "Interest Adjustment Date"},
        "plugin": "datepicker",
        "optgroup": "attributes",
        "plugin_config": {
            "format": "yyyy-mm-dd",
            "todayBtn": "linked",
            "autoclose": True,
            "todayHighlight": True,
        },
    },
    {
        "id": "attrs__contract_end_date",
        "type": "date",
        "field": "attrs__contract_end_date",
        "label": {"en": "Contract End Date"},
        "plugin": "datepicker",
        "optgroup": "attributes",
        "plugin_config": {
            "format": "yyyy-mm-dd",
            "todayBtn": "linked",
            "autoclose": True,
            "todayHighlight": True,
        },
    },
    {
        "id": "attrs__category",
        "type": "string",
        "field": "attrs__category",
        "input": "text",
        "label": {"en": "Category"},
        "optgroup": "attributes",
    },
    {
        "id": "attrs__building_id",
        "type": "string",
        "field": "attrs__building_id",
        "input": "text",
        "label": {"en": "Building ID"},
        "optgroup": "attributes",
    },
    {
        "id": "attrs__phys_link",
        "type": "string",
        "field": "attrs__phys_link",
        "input": "checkbox",
        "label": {"en": "Physical Link"},
        "values": [
            "row house (one side)",
            "semi-detached",
            "single-detached",
            "integrated",
            "row house",
        ],
        "optgroup": "attributes",
        "operators": ["in", "not_in", "is_null", "is_not_null"],
    },
    {
        "id": "attrs__const_type",
        "type": "string",
        "field": "attrs__const_type",
        "input": "checkbox",
        "label": {"en": "Construction Type"},
        "values": [
            "attic",
            "single-storey",
            "staggered-level",
            "modular prefab",
            "full-storey",
        ],
        "optgroup": "attributes",
         "operators": ["in", "not_in", "is_null", "is_not_null"],
    },
    {
        "id": "attrs__owner_date",
        "type": "date",
        "field": "attrs__owner_date",
        "label": {"en": "Owner Date"},
        "plugin": "datepicker",
        "optgroup": "attributes",
        "plugin_config": {
            "format": "yyyy-mm-dd",
            "todayBtn": "linked",
            "autoclose": True,
            "todayHighlight": True,
        },
    },
    {
        "id": "attrs__owner_type",
        "type": "string",
        "field": "attrs__owner_type",
        "input": "checkbox",
        "label": {"en": "Owner Type"},
        "values": ["moral", "physical"],
        "optgroup": "attributes",
        "operators": ["in", "not_in", "is_null", "is_not_null"],
    },
    {
        "id": "attrs__owner_status",
        "type": "string",
        "field": "attrs__owner_status",
        "input": "checkbox",
        "label": {"en": "Owner Status"},
        "values": [
            "undivided co-owner",
            "lessor of public land",
            "landowner",
            "condo owner",
            "other",
            "tenant of tax-exempt building",
            "lessor",
            "building owner on public land",
            "trailer building owner",
        ],
        "optgroup": "attributes",
        "operators": ["in", "not_in", "is_null", "is_not_null"],
    },
    {
        "id": "attrs__lot_lin_dim",
        "type": "double",
        "field": "attrs__lot_lin_dim",
        "input": "number",
        "label": {"en": "Lot Linear Dimension"},
        "optgroup": "attributes",
        "validation": {"min": 0, "step": 0.01},
    },
    {
        "id": "attrs__lot_area",
        "type": "double",
        "field": "attrs__lot_area",
        "input": "number",
        "label": {"en": "Lot Area"},
        "optgroup": "attributes",
        "validation": {"min": 0, "step": 0.01},
    },
    {
        "id": "attrs__apprais_date",
        "type": "date",
        "field": "attrs__apprais_date",
        "label": {"en": "Appraisal Date"},
        "plugin": "datepicker",
        "optgroup": "attributes",
        "plugin_config": {
            "format": "yyyy-mm-dd",
            "todayBtn": "linked",
            "autoclose": True,
            "todayHighlight": True,
        },
    },
    {
        "id": "attrs__lot_value",
        "type": "double",
        "field": "attrs__lot_value",
        "input": "number",
        "label": {"en": "Lot Value"},
        "optgroup": "attributes",
        "validation": {"min": 0, "step": 0.01},
    },
    {
        "id": "attrs__building_value",
        "type": "double",
        "field": "attrs__building_value",
        "input": "number",
        "label": {"en": "Building Value"},
        "optgroup": "attributes",
        "validation": {"min": 0, "step": 0.01},
    },
    {
        "id": "attrs__value",
        "type": "double",
        "field": "attrs__value",
        "input": "number",
        "label": {"en": "Value"},
        "optgroup": "attributes",
        "validation": {"min": 0, "step": 0.01},
    },
    {
        "id": "attrs__prev_value",
        "type": "double",
        "field": "attrs__prev_value",
        "input": "number",
        "label": {"en": "Previous Value"},
        "optgroup": "attributes",
        "validation": {"min": 0, "step": 0.01},
    },
]


survey_schema = {
    "appendages": {
        "type": "text",
        "label": {"en": "Appendages"},
        "widget": "multi_checkbox_specify",
        "options": [
            {"val": "balconies", "label": {"en": "Balconies"}, "pos": 0},
            {
                "val": "vestibules",
                "label": {"en": "Exterior Vestibules"},
                "pos": 1,
            },
            {
                "val": "canopies_eaves",
                "label": {"en": "Roof overhangs/eaves"},
                "pos": 2,
            },
            {
                "val": "porches_stoops",
                "label": {"en": "Porches/stoops"},
                "pos": 3,
            },
            {"val": "other", "label": {"en": "Other (specify)"}, "pos": 4},
        ],
        "question_text": {
            "en": "Select any and all significant appendages to the building faces."
        },
        "widget_config": {
            "attrs": {"class": "survey-1col"},
            "specify_input_type": "text",
            "specify_option_value": "other",
        },
        "pos": 7,
    },
    "num_storeys": {
        "type": "integer",
        "label": {"en": "Number of Storeys"},
        "widget": "radio_w_specify",
        "options": [
            {
                "val": "num_storeys",
                "label": {"en": "Number of storeys"},
                "pos": 0,
            },
            {"val": None, "label": {"en": "Unsure"}, "pos": 1},
        ],
        "question_text": {
            "en": "How many storeys above-ground does the building have?"
        },
        "widget_config": {
            "attrs": {"class": "survey-1col"},
            "specify_input_type": "number",
            "specify_option_value": "num_storeys",
        },
        "pos": 4,
    },
    "has_basement": {
        "type": "boolean",
        "label": {"en": "Has Basement"},
        "widget": "radio",
        "options": [
            {"val": True, "label": {"en": "Yes"}, "pos": 0},
            {"val": False, "label": {"en": "No"}, "pos": 1},
            {"val": None, "label": {"en": "Unsure"}, "pos": 2},
        ],
        "question_text": {"en": "Does the building appear to have a basement?"},
        "widget_config": {"attrs": {"class": "survey-1col"}},
        "pos": 5,
    },
    "roof_geometry": {
        "type": "text",
        "label": {"en": "Roof Geometry"},
        "widget": "multi_checkbox_required",
        "options": [
            {"val": "flat", "label": {"en": "Flat"}, "pos": 0},
            {"val": "curved", "label": {"en": "Curved"}, "pos": 1},
            {"val": "unsure", "label": {"en": "Unsure"}, "pos": 2},
            {"val": "complex", "label": {"en": "Complex"}, "pos": 3},
            {"val": "pitch_low", "label": {"en": "Low Pitched"}, "pos": 4},
            {"val": "pitch_high", "label": {"en": "High Pitched"}, "pos": 5},
        ],
        "question_text": {"en": "Select all that describes the roof geometry."},
        "widget_config": {"attrs": {"class": "survey-3col"}},
        "pos": 12,
    },
    "facade_condition": {
        "type": "boolean",
        "label": {"en": "Facade Condition"},
        "widget": "radio",
        "options": [
            {"val": True, "label": {"en": "Yes"}, "pos": 0},
            {"val": False, "label": {"en": "No"}, "pos": 1},
            {"val": None, "label": {"en": "Unsure"}, "pos": 2},
        ],
        "question_text": {
            "en": "Are the façades in poor condition and in need of replacement?"
        },
        "widget_config": {"attrs": {"class": "survey-1col"}},
        "pos": 9,
    },
    "new_or_renovated": {
        "type": "text",
        "label": {"en": "New or Renovated"},
        "widget": "multi_checkbox",
        "options": [
            {"val": "newly_built", "label": {"en": "Newly built"}, "pos": 0},
            {
                "val": "recently_renovated",
                "label": {"en": "Recently renovated"},
                "pos": 1,
            },
        ],
        "question_text": {
            "en": "Does the building look newly built or recently renovated?"
        },
        "pos": 13,
    },
    "exterior_cladding": {
        "type": "text",
        "label": {"en": "Exterior Cladding"},
        "widget": "multi_checkbox_required_specify",
        "options": [
            {"val": "wood", "label": {"en": "Wood"}, "pos": 0},
            {"val": "metal", "label": {"en": "Metal"}, "pos": 1},
            {"val": "vinyl", "label": {"en": "Vinyl"}, "pos": 2},
            {"val": "plaster", "label": {"en": "Plaster"}, "pos": 3},
            {"val": "concrete", "label": {"en": "Concrete"}, "pos": 4},
            {"val": "curtain_wall", "label": {"en": "Curtain Wall"}, "pos": 5},
            {
                "val": "brick_masonry",
                "label": {"en": "Brick Masonry"},
                "pos": 6,
            },
            {
                "val": "stone_masonry",
                "label": {"en": "Stone Masonry"},
                "pos": 7,
            },
            {"val": "unsure", "label": {"en": "Unsure"}, "pos": 8},
            {"val": "other", "label": {"en": "Other (Specify)"}, "pos": 9},
        ],
        "question_text": {
            "en": "Select all widgets of exterior cladding does the building appear to have."
        },
        "widget_config": {
            "attrs": {"class": "survey-3col"},
            "specify_input_type": "text",
            "specify_option_value": "other",
        },
        "pos": 8,
    },
    "has_simple_volume": {
        "type": "boolean",
        "label": {"en": "Simple Volume"},
        "widget": "radio",
        "options": [
            {"val": True, "label": {"en": "Yes"}, "pos": 0},
            {"val": False, "label": {"en": "No"}, "pos": 1},
        ],
        "question_text": {"en": "Does the building have a simple volumetric form?"},
        "pos": 3,
    },
    "site_obstructions": {
        "type": "text",
        "label": {"en": "Site Obstructions"},
        "widget": "multi_checkbox_specify",
        "options": [
            {
                "val": "trees_or_landscaping",
                "label": {"en": "Important trees or landscaping"},
                "pos": 0,
            },
            {"val": "buildings", "label": {"en": "Buildings"}, "pos": 1},
            {
                "val": "overhead_wires",
                "label": {
                    "en": "Overhead wires, incl. those blocking general access to site"
                },
                "pos": 2,
            },
            {"val": "other", "label": {"en": "Other (Specify)"}, "pos": 3},
        ],
        "question_text": {
            "en": "Select any and all obstructions to machine access around the building."
        },
        "pos": 6,
    },
    "window_wall_ratio": {
        "type": "boolean",
        "label": {"en": "Window-to-Wall Ratio"},
        "widget": "radio",
        "options": [
            {"val": True, "label": {"en": "Yes"}, "pos": 0},
            {"val": False, "label": {"en": "No"}, "pos": 1},
            {"val": None, "label": {"en": "Unsure"}, "pos": 2},
        ],
        "question_text": {
            "en": "Does glazing make up more than 40% of the total visible façade area?"
        },
        "widget_config": {"attrs": {"class": "survey-1col"}},
        "pos": 10,
    },
    "has_simple_footprint": {
        "type": "boolean",
        "label": {"en": "Simple Footprint"},
        "widget": "radio",
        "options": [
            {"val": True, "label": {"en": "Yes"}, "pos": 0},
            {"val": False, "label": {"en": "No"}, "pos": 1},
        ],
        "question_text": {"en": "Does the building have a simple footprint?"},
        "pos": 2,
    },
    "self_similar_cluster": {
        "type": "integer",
        "label": {"en": "Self Similar Cluster"},
        "widget": "radio_w_specify",
        "options": [
            {
                "val": "num_buildings_in_cluster",
                "label": {"en": "Buildings in cluster"},
                "pos": 0,
            },
            {"val": None, "label": {"en": "No"}, "pos": 1},
        ],
        "question_text": {
            "en": "Is the building part of a self-similar cluster? If so, how many buildings are in the cluster?"
        },
        "widget_config": {
            "specify_input_type": "number",
            "specify_option_value": "num_buildings_in_cluster",
        },
        "pos": 1,
    },
    "large_irregular_windows": {
        "type": "text",
        "label": {"en": "Large/Irregular Windows"},
        "widget": "multi_checkbox",
        "options": [
            {
                "val": "irregular_windows",
                "label": {"en": "Irregularly shaped"},
                "pos": 1,
            },
            {
                "val": "very_large_windows",
                "label": {"en": "Very large"},
                "pos": 0,
            },
        ],
        "question_text": {
            "en": "Are there very large and/or irregularly shaped windows?"
        },
        "widget_config": {"attrs": {"class": "survey-1col"}},
        "pos": 11,
    },
}
